### ISSUE TITLE
(Request) Re-code/Delete part of the code that causes: (module 'cv2.cv2' has no attribute 'freetype').

### ISSUE THREAD

**Issue by wast0** [kkoomen/qbr#23]
Hi @kkoomen, first of all, I know the issue regarding:  (module 'cv2.cv2' has no attribute 'freetype') has been already discussed. Because I could not find any solution to this, i was wondering if you knew any other method or way to "re-code" the project so that the problematic part of the code is eliminated, (even if this means that it will have less functionalities). Thank you in advanced, (amazing work btw).

**Comment by kkoomen** [comment]
Thanks for the nice words, but I won't fix an issue that is not related to the project. I just followed the [Installation](https://github.com/kkoomen/qbr#installation) process on a fresh machine and had no problems. If you experience this problem then you have to fix this in your local environment, because this shouldn't happen with a normal/fresh python installation.

To repeat myself in yet another issue: Make sure you run `pip3 install opencv-python` _and then_ `pip3 install opencv-contrib-python`. The order here is important. Make sure to remove these two packages first before installing them in the correct order.

**Comment by wast0** [comment]
Did you make it work on Windows or Linux? Plus, what Python version did you use? 
Thanks.

**Comment by kkoomen** [comment]
In [this](https://github.com/kkoomen/qbr/issues/23#issuecomment-896030170) comment I did test it on a fresh macOS install. I don't have Windows and thus won't support it for any of the projects I've done. If people have issues on Windows then those can be fixed by them by submitting a PR to this project.
